### ISSUE TITLE
Design a Logo

### ISSUE THREAD

**Issue by SachithMayantha** [SachithMayantha/recipe-app#1]
Need a creative logo for this site. (Please consider about page colours)

**Comment by Kharanshu31** [comment]
i want to work on this

**Comment by SachithMayantha** [comment]
Sure. @Kharanshu31  Let's design. Matching logo colours with the background.

**Comment by Kharanshu31** [comment]
where to make changes in src folder?

**Comment by SachithMayantha** [comment]
Check App.js and App.css files.

**Comment by Kharanshu31** [comment]
you have an image which we can use as a logo?

**Comment by SachithMayantha** [comment]
No. You can design it as you wish.
@Kharanshu31  If you can, make it responsive
